<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tour;
use Carbon\Carbon;

class BangkokTours2Seeder extends Seeder
{
    public function run(): void
    {
        $tours = [
            // BKK 06
            [
                'name' => 'Bangkok Free & Easy Shopping 4D3N',
                'description' => 'Paket fleksibel untuk Anda yang suka belanja dan eksplorasi mandiri! Nikmati city tour singkat ke Wat Arun dan Platinum Mall, lalu hari bebas untuk menjelajah sesuai keinginan. Tersedia opsional E-Scooter Tour untuk eksplorasi hidden gems Bangkok. Cocok untuk shopper dan explorer.',
                'price' => 1850000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Bangkok, Thailand',
                'category_id' => 6,
                'max_participants' => 30,
                'booked_participants' => 0,
                'start_date' => Carbon::parse('2026-01-15 08:00'),
                'end_date' => Carbon::parse('2026-01-18 18:00'),
                'highlights' => [
                    'Wat Arun (Temple of Dawn)',
                    'Platinum Fashion Mall',
                    'Asiatique Riverfront Night Market',
                    'FREE DAY for shopping',
                    'Opsional E-Scooter Tour (Rp250K)',
                    'Icon Siam & Sook Siam Floating Market',
                ],
                'included' => [
                    'Makan sesuai itinerary (3 Breakfast)',
                    'Hotel bintang 3 (Thomson/Princeton Bangkok)',
                    'Transportasi Bus AC + Wi-Fi + Karaoke',
                    'Tiket masuk objek wisata sesuai itinerary',
                    'Guide lokal berbahasa Indonesia',
                    'Handling bandara Soekarno-Hatta',
                    'Asuransi wisata',
                    'Air mineral selama tour',
                    'Tipping guide IDR 350.000/pax',
                ],
                'excluded' => [
                    'Tiket pesawat PP',
                    'Bagasi pesawat tidak terdaftar',
                    'Makan siang & malam (kecuali sarapan)',
                    'Optional Tour (E-Scooter Rp250K, Dinner Cruise)',
                    'Keperluan pribadi',
                ],
                'departure_location' => 'Jakarta (CGK Airport) - bertemu Tim Handling',
                'available_from' => Carbon::parse('2026-01-01'),
                'available_until' => Carbon::parse('2026-12-20'),
                'is_recommended' => false,
                'recommendation_order' => null,
                'discount_percentage' => null,
                'promo_end_date' => null,
                'promo_label' => null,
            ],
            
            // BKK 07
            [
                'name' => 'Khaoyai Toscana Valley Getaway 4D3N',
                'description' => 'Nikmati suasana Eropa di Thailand! Jelajahi Khaoyai dengan kunjungan ke Hokkaido Flower Park, Toscana Valley yang cantik, Toy Museum, dan Suwan Corn Farm. Kembali ke Bangkok untuk city tour klasik dan gratis Calypso Cabaret Show. Perpaduan sempurna antara alam, foto estetik, dan hiburan.',
                'price' => 2800000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Bangkok & Khaoyai, Thailand',
                'category_id' => 6,
                'max_participants' => 30,
                'booked_participants' => 0,
                'start_date' => Carbon::parse('2026-01-15 08:00'),
                'end_date' => Carbon::parse('2026-01-18 18:00'),
                'highlights' => [
                    'Hokkaido Flower Park',
                    'Toscana Valley (photo spot ala Italia)',
                    'Toy Museum & Ban Mai Chay Nam Restaurant',
                    'Suwan Corn Farm',
                    'Wat Arun & Chaophraya River',
                    'Calypso Cabaret Show GRATIS',
                ],
                'included' => [
                    'Makan sesuai itinerary (3 Breakfast, 2 Lunch, 1 Dinner)',
                    'Hotel bintang 3 (Thomson/Princeton Bangkok)',
                    'Transportasi Bus AC + Wi-Fi + Karaoke',
                    'Tiket masuk objek wisata sesuai itinerary',
                    'Guide lokal berbahasa Indonesia',
                    'Handling bandara Soekarno-Hatta',
                    'Asuransi wisata',
                    'Air mineral selama tour',
                    'Tipping guide IDR 350.000/pax',
                ],
                'excluded' => [
                    'Tiket pesawat PP',
                    'Bagasi pesawat tidak terdaftar',
                    'Optional Tour',
                    'Keperluan pribadi',
                ],
                'departure_location' => 'Jakarta (CGK Airport) - bertemu Tim Handling',
                'available_from' => Carbon::parse('2026-01-01'),
                'available_until' => Carbon::parse('2026-12-20'),
                'is_recommended' => true,
                'recommendation_order' => 6,
                'discount_percentage' => null,
                'promo_end_date' => null,
                'promo_label' => null,
            ],
            
            // BKK 08
            [
                'name' => 'Ayutthaya Historical & Heritage 4D3N',
                'description' => 'Jelajahi kejayaan masa lalu Thailand di Ayutthaya Historical Park, situs warisan dunia. Kunjungi Wat Chai Watthanaram dan Wat Mahathat yang ikonik. Kembali ke Bangkok untuk city tour dan gratis Calypso Cabaret Show. Paket ideal untuk pecinta sejarah dan budaya.',
                'price' => 3150000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Bangkok & Ayutthaya, Thailand',
                'category_id' => 3, // Cultural
                'max_participants' => 30,
                'booked_participants' => 0,
                'start_date' => Carbon::parse('2026-01-15 08:00'),
                'end_date' => Carbon::parse('2026-01-18 18:00'),
                'highlights' => [
                    'Ayutthaya Historical Park (UNESCO)',
                    'Wat Chai Watthanaram',
                    'Wat Mahathat (patung Buddha di akar pohon)',
                    'Jodd Fairs Night Market',
                    'Wat Arun & Chaophraya River',
                    'Calypso Cabaret Show GRATIS',
                ],
                'included' => [
                    'Makan sesuai itinerary (3 Breakfast, 2 Lunch, 1 Dinner)',
                    'Hotel bintang 3 (Thomson/Princeton Bangkok)',
                    'Transportasi Bus AC + Wi-Fi + Karaoke',
                    'Tiket masuk objek wisata sesuai itinerary',
                    'Guide lokal berbahasa Indonesia',
                    'Handling bandara Soekarno-Hatta',
                    'Asuransi wisata',
                    'Air mineral selama tour',
                    'Tipping guide IDR 350.000/pax',
                ],
                'excluded' => [
                    'Tiket pesawat PP',
                    'Bagasi pesawat tidak terdaftar',
                    'Optional Tour',
                    'Keperluan pribadi',
                ],
                'departure_location' => 'Jakarta (CGK Airport) - bertemu Tim Handling',
                'available_from' => Carbon::parse('2026-01-01'),
                'available_until' => Carbon::parse('2026-12-20'),
                'is_recommended' => true,
                'recommendation_order' => 7,
                'discount_percentage' => null,
                'promo_end_date' => null,
                'promo_label' => null,
            ],
            
            // BKK 09
            [
                'name' => 'Kanchanaburi Safari & Death Railway 4D3N',
                'description' => 'Petualangan seru di Kanchanaburi! Nikmati Kanchanaburi Skywalk, naik kereta di Tham Krasae Bridge (Death Railway), dan interaksi dengan jerapah di Safari Park. Kembali ke Bangkok untuk city tour dan gratis Calypso Cabaret Show. Kombinasi sempurna antara sejarah, petualangan, dan satwa.',
                'price' => 3350000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Bangkok & Kanchanaburi, Thailand',
                'category_id' => 6,
                'max_participants' => 30,
                'booked_participants' => 0,
                'start_date' => Carbon::parse('2026-01-15 08:00'),
                'end_date' => Carbon::parse('2026-01-18 18:00'),
                'highlights' => [
                    'Kanchanaburi Skywalk',
                    'Death Railway & Tham Krasae Bridge',
                    'Kanchanaburi Safari Park (interact with Giraffe)',
                    'Elephant Show',
                    'Wat Arun & Chaophraya River',
                    'Calypso Cabaret Show GRATIS',
                ],
                'included' => [
                    'Makan sesuai itinerary (3 Breakfast, 2 Lunch, 1 Dinner)',
                    'Hotel bintang 3 (Thomson/Princeton Bangkok)',
                    'Transportasi Bus AC + Wi-Fi + Karaoke',
                    'Tiket masuk objek wisata sesuai itinerary',
                    'Guide lokal berbahasa Indonesia',
                    'Handling bandara Soekarno-Hatta',
                    'Asuransi wisata',
                    'Air mineral selama tour',
                    'Tipping guide IDR 350.000/pax',
                ],
                'excluded' => [
                    'Tiket pesawat PP',
                    'Bagasi pesawat tidak terdaftar',
                    'Optional Tour',
                    'Keperluan pribadi',
                ],
                'departure_location' => 'Jakarta (CGK Airport) - bertemu Tim Handling',
                'available_from' => Carbon::parse('2026-01-01'),
                'available_until' => Carbon::parse('2026-12-20'),
                'is_recommended' => true,
                'recommendation_order' => 8,
                'discount_percentage' => null,
                'promo_end_date' => null,
                'promo_label' => null,
            ],
            
            // BKK 10
            [
                'name' => 'Dream World & Snow Town Fun 4D3N',
                'description' => 'Liburan seru untuk keluarga! Habiskan sehari penuh di Dream World, taman hiburan terbesar Bangkok dengan Snow Town, Dream Garden, Fantasy Land, dan Adventure Land. Lengkap dengan city tour Bangkok dan gratis Calypso Cabaret Show. Cocok untuk family dan kids.',
                'price' => 3200000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Bangkok, Thailand',
                'category_id' => 6,
                'max_participants' => 30,
                'booked_participants' => 0,
                'start_date' => Carbon::parse('2026-01-15 08:00'),
                'end_date' => Carbon::parse('2026-01-18 18:00'),
                'highlights' => [
                    'Dream World Happy Land (unlimited time)',
                    'Snow Town (salju buatan)',
                    'Fantasy Land & Adventure Land',
                    'MBK Shopping Mall',
                    'Wat Arun & Chaophraya River',
                    'Calypso Cabaret Show GRATIS',
                ],
                'included' => [
                    'Makan sesuai itinerary (3 Breakfast, 1 Lunch at Dream World, 1 Dinner)',
                    'Hotel bintang 3 (Thomson/Princeton Bangkok)',
                    'Transportasi Bus AC + Wi-Fi + Karaoke',
                    'Tiket masuk Dream World + Snow Town',
                    'Tiket masuk objek wisata lainnya',
                    'Guide lokal berbahasa Indonesia',
                    'Handling bandara Soekarno-Hatta',
                    'Asuransi wisata',
                    'Air mineral selama tour',
                    'Tipping guide IDR 350.000/pax',
                ],
                'excluded' => [
                    'Tiket pesawat PP',
                    'Bagasi pesawat tidak terdaftar',
                    'Optional Tour',
                    'Keperluan pribadi',
                ],
                'departure_location' => 'Jakarta (CGK Airport) - bertemu Tim Handling',
                'available_from' => Carbon::parse('2026-01-01'),
                'available_until' => Carbon::parse('2026-12-20'),
                'is_recommended' => true,
                'recommendation_order' => 9,
                'discount_percentage' => null,
                'promo_end_date' => null,
                'promo_label' => null,
            ],
            
            // BKK 11
            [
                'name' => 'Safari World Marine Park Adventure 4D3N',
                'description' => 'Petualangan seru di Safari World & Marine Park! Saksikan berbagai pertunjukan menarik: Spy War Show, Cowboy Show, dan animal show. Nikmati interaksi dengan satwa dan foto bersama. Lengkap dengan city tour Bangkok dan gratis Calypso Cabaret Show. Favorit keluarga!',
                'price' => 3200000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Bangkok, Thailand',
                'category_id' => 6,
                'max_participants' => 30,
                'booked_participants' => 0,
                'start_date' => Carbon::parse('2026-01-15 08:00'),
                'end_date' => Carbon::parse('2026-01-18 18:00'),
                'highlights' => [
                    'Safari World + Marine Park',
                    'Spy War Show & Cowboy Show',
                    'Animal Shows & Photo Ops',
                    'MBK Shopping Mall',
                    'Wat Arun & Chaophraya River',
                    'Calypso Cabaret Show GRATIS',
                ],
                'included' => [
                    'Makan sesuai itinerary (3 Breakfast, 1 Lunch at Safari World, 1 Dinner)',
                    'Hotel bintang 3 (Thomson/Princeton Bangkok)',
                    'Transportasi Bus AC + Wi-Fi + Karaoke',
                    'Tiket masuk Safari World + Marine Park',
                    'Tiket masuk objek wisata lainnya',
                    'Guide lokal berbahasa Indonesia',
                    'Handling bandara Soekarno-Hatta',
                    'Asuransi wisata',
                    'Air mineral selama tour',
                    'Tipping guide IDR 350.000/pax',
                ],
                'excluded' => [
                    'Tiket pesawat PP',
                    'Bagasi pesawat tidak terdaftar',
                    'Optional Tour',
                    'Keperluan pribadi',
                ],
                'departure_location' => 'Jakarta (CGK Airport) - bertemu Tim Handling',
                'available_from' => Carbon::parse('2026-01-01'),
                'available_until' => Carbon::parse('2026-12-20'),
                'is_recommended' => true,
                'recommendation_order' => 10,
                'discount_percentage' => null,
                'promo_end_date' => null,
                'promo_label' => null,
            ],
        ];

        foreach ($tours as $tourData) {
            Tour::create($tourData);
        }

        $this->command->info('✅ 6 paket Bangkok berhasil ditambahkan!');
    }
}
